import Foundation

enum AppTabID: Hashable {
    case live
    case history
    case settings
}

@MainActor
final class AppLanguageCenter: ObservableObject {
    @Published var localeCode: String

    init(localeCode: String = "zh-Hans") {
        self.localeCode = localeCode
    }

    func setLocale(_ locale: String) {
        localeCode = locale
    }

    func text(_ key: String) -> String {
        let map = dictionary(for: localeCode)
        return map[key] ?? key
    }

    private func dictionary(for locale: String) -> [String: String] {
        if locale.hasPrefix("en") {
            return english
        }
        if locale.hasPrefix("ja") {
            return japanese
        }
        return chinese
    }

    private let chinese: [String: String] = [
        "tab.live": "实时",
        "tab.history": "历史",
        "tab.settings": "设置",
        "status": "状态",
        "start": "开始",
        "stop": "停止",
        "clear": "清空",
        "refine": "润色",
        "speak": "朗读",
        "transcribeFile": "转录文件",
        "partial": "实时识别",
        "final": "最终文本",
        "live.codexOAuthLogin": "Codex 登录",
        "live.oauthOpenBrowser": "打开浏览器",
        "live.oauthClose": "关闭",
        "history.search": "搜索历史文本",
        "history.refresh": "刷新",
        "history.exportTxt": "导出 TXT",
        "history.exportMd": "导出 MD",
        "history.exportJson": "导出 JSON",
        "history.audioAssets": "音频资产",
        "history.sessions": "会话列表",
        "history.segments": "转录片段",
        "history.exports": "导出",
        "history.noAudioAssets": "此会话暂无可用音频",
        "history.playAudio": "播放原音频",
        "history.stopAudio": "停止播放",
        "history.retranscribeAudio": "重转录",
        "history.deleteAudio": "删除音频",
        "history.deleteSession": "删除会话",
        "settings.apiKey": "OpenAI API Key",
        "settings.sectionGeneral": "通用",
        "settings.sectionAccess": "凭据与登录",
        "settings.sectionPipeline": "文本管线",
        "settings.sectionModels": "本地模型",
        "settings.locale": "界面语言",
        "settings.primaryStt": "主转录引擎",
        "settings.localFallback": "本地兜底引擎",
        "settings.refinePrimary": "润色主引擎",
        "settings.ttsPrimary": "TTS 主引擎",
        "settings.hotkey": "全局快捷键",
        "settings.hotkeyCurrent": "当前快捷键",
        "settings.hotkeyCaptureStart": "录制快捷键",
        "settings.hotkeyCaptureStop": "停止录制",
        "settings.hotkeyReset": "恢复默认",
        "settings.hotkeyHint": "请使用至少一个修饰键（⌘ / ⇧ / ⌥ / ⌃）。",
        "settings.hotkeyRecordingHint": "请按下新的快捷键，按 Esc 取消。",
        "settings.hotkeyNeedModifier": "快捷键至少需要一个修饰键",
        "settings.hotkeyCaptureCancelled": "快捷键录制已取消",
        "settings.codexToken": "Codex Access Token",
        "settings.codexAccount": "Codex Account ID",
        "settings.importCodex": "从 Codex 导入",
        "settings.codexOAuth": "Codex OAuth 登录",
        "settings.codexOAuthStatus": "登录状态",
        "settings.codexOAuthSource": "认证文件",
        "settings.codexOAuthLastRefresh": "最近刷新",
        "settings.codexOAuthCode": "设备码",
        "settings.codexOAuthCopyCode": "复制设备码",
        "settings.codexOAuthCopyURL": "复制链接",
        "settings.codexAuthMode": "认证方式",
        "settings.codexAuthModeOAuth": "OAuth 设备登录",
        "settings.codexAuthModeManual": "手动填写 Token",
        "settings.codexOAuthStep1": "启动设备登录",
        "settings.codexOAuthStep2": "打开授权链接并复制设备码",
        "settings.codexOAuthStep3": "完成授权后刷新状态",
        "settings.codexManualTokenHint": "手动模式下仅填写 Token 与 Account ID，不启用 OAuth 流程。",
        "settings.codexOAuthStart": "开始设备登录",
        "settings.codexOAuthCancel": "取消",
        "settings.codexOAuthRefresh": "刷新状态",
        "settings.codexOAuthLogout": "退出登录",
        "settings.defaultPipeline": "默认文本管线",
        "settings.noPipeline": "无可用管线",
        "settings.pipelineEditor": "文本管线编辑器",
        "settings.pipelineList": "编辑中的管线",
        "settings.pipelineNew": "新建管线",
        "settings.pipelineDuplicate": "复制管线",
        "settings.pipelineDelete": "删除管线",
        "settings.pipelineName": "管线名称",
        "settings.pipelineEnabled": "启用管线",
        "settings.pipelineStages": "处理阶段",
        "settings.stageEnabled": "启用",
        "settings.stageType": "阶段类型",
        "settings.stageAdd": "添加阶段",
        "settings.stageMoveUp": "上移",
        "settings.stageMoveDown": "下移",
        "settings.stageRemove": "删除阶段",
        "settings.stageConfigPattern": "正则 Pattern",
        "settings.stageConfigReplacement": "替换为",
        "settings.stageConfigTemplate": "模板（{{text}}）",
        "settings.stageConfigStyle": "注释风格",
        "settings.stageConfigPrompt": "LLM Prompt",
        "stage.smartPunctuation": "智能标点",
        "stage.fillerRemoval": "去填充词",
        "stage.whitespaceNormalize": "空白规范化",
        "stage.regexReplace": "正则替换",
        "stage.templateApply": "模板应用",
        "stage.codeCommentTemplate": "代码注释模板",
        "stage.llmRewrite": "LLM 改写",
        "settings.models": "本地模型",
        "settings.modelRefresh": "刷新模型状态",
        "settings.modelPath": "安装路径",
        "settings.modelQuickStatus": "快速状态",
        "settings.modelVerifyStatus": "校验状态",
        "settings.modelVerify": "校验",
        "settings.modelRetry": "重试下载",
        "settings.modelCleanup": "清理残留",
        "settings.modelQuickInstalled": "已安装",
        "settings.modelQuickSizeMismatch": "大小不匹配",
        "settings.modelQuickPartialOnly": "仅有未完成文件",
        "settings.modelQuickNotInstalled": "未安装",
        "settings.modelVerifyChecking": "校验中",
        "settings.modelVerifyNotChecked": "未校验",
        "settings.modelVerifyValid": "校验通过",
        "settings.modelVerifyMissing": "文件缺失",
        "settings.modelVerifySizeMismatch": "大小不匹配",
        "settings.modelVerifyChecksumMismatch": "哈希不匹配",
        "settings.modelVerifyInvalid": "校验失败",
        "settings.download": "下载",
        "settings.remove": "删除",
        "settings.save": "保存",
        "settings.saved": "已保存",
    ]

    private let english: [String: String] = [
        "tab.live": "Live",
        "tab.history": "History",
        "tab.settings": "Settings",
        "status": "Status",
        "start": "Start",
        "stop": "Stop",
        "clear": "Clear",
        "refine": "Refine",
        "speak": "Speak",
        "transcribeFile": "Transcribe File",
        "partial": "Partial",
        "final": "Final",
        "live.codexOAuthLogin": "Codex Login",
        "live.oauthOpenBrowser": "Open Browser",
        "live.oauthClose": "Close",
        "history.search": "Search transcript history",
        "history.refresh": "Refresh",
        "history.exportTxt": "Export TXT",
        "history.exportMd": "Export MD",
        "history.exportJson": "Export JSON",
        "history.audioAssets": "Audio Assets",
        "history.sessions": "Sessions",
        "history.segments": "Segments",
        "history.exports": "Export",
        "history.noAudioAssets": "No audio available for this session",
        "history.playAudio": "Play Audio",
        "history.stopAudio": "Stop",
        "history.retranscribeAudio": "Retranscribe",
        "history.deleteAudio": "Delete Audio",
        "history.deleteSession": "Delete Session",
        "settings.apiKey": "OpenAI API Key",
        "settings.sectionGeneral": "General",
        "settings.sectionAccess": "Credentials",
        "settings.sectionPipeline": "Pipeline",
        "settings.sectionModels": "Local Models",
        "settings.locale": "UI Language",
        "settings.primaryStt": "Primary STT",
        "settings.localFallback": "Local Fallback Engine",
        "settings.refinePrimary": "Primary Refine Provider",
        "settings.ttsPrimary": "Primary TTS Provider",
        "settings.hotkey": "Global Hotkey",
        "settings.hotkeyCurrent": "Current Hotkey",
        "settings.hotkeyCaptureStart": "Record Hotkey",
        "settings.hotkeyCaptureStop": "Stop Capture",
        "settings.hotkeyReset": "Reset Default",
        "settings.hotkeyHint": "Use at least one modifier key (⌘ / ⇧ / ⌥ / ⌃).",
        "settings.hotkeyRecordingHint": "Press a new shortcut now, press Esc to cancel.",
        "settings.hotkeyNeedModifier": "Hotkey requires at least one modifier key",
        "settings.hotkeyCaptureCancelled": "Hotkey capture cancelled",
        "settings.codexToken": "Codex Access Token",
        "settings.codexAccount": "Codex Account ID",
        "settings.importCodex": "Import from Codex",
        "settings.codexOAuth": "Codex OAuth Login",
        "settings.codexOAuthStatus": "Status",
        "settings.codexOAuthSource": "Auth File",
        "settings.codexOAuthLastRefresh": "Last Refresh",
        "settings.codexOAuthCode": "Device Code",
        "settings.codexOAuthCopyCode": "Copy Code",
        "settings.codexOAuthCopyURL": "Copy Link",
        "settings.codexAuthMode": "Auth Mode",
        "settings.codexAuthModeOAuth": "OAuth Device Login",
        "settings.codexAuthModeManual": "Manual Token",
        "settings.codexOAuthStep1": "Start device login",
        "settings.codexOAuthStep2": "Open the auth link and copy the device code",
        "settings.codexOAuthStep3": "After confirming in browser, refresh status",
        "settings.codexManualTokenHint": "Manual mode accepts token/account only and does not run OAuth flow.",
        "settings.codexOAuthStart": "Start Device Login",
        "settings.codexOAuthCancel": "Cancel",
        "settings.codexOAuthRefresh": "Refresh Status",
        "settings.codexOAuthLogout": "Logout",
        "settings.defaultPipeline": "Default Text Pipeline",
        "settings.noPipeline": "No pipelines available",
        "settings.pipelineEditor": "Text Pipeline Editor",
        "settings.pipelineList": "Editing Pipeline",
        "settings.pipelineNew": "New Pipeline",
        "settings.pipelineDuplicate": "Duplicate",
        "settings.pipelineDelete": "Delete",
        "settings.pipelineName": "Pipeline Name",
        "settings.pipelineEnabled": "Enable Pipeline",
        "settings.pipelineStages": "Stages",
        "settings.stageEnabled": "Enabled",
        "settings.stageType": "Stage Type",
        "settings.stageAdd": "Add Stage",
        "settings.stageMoveUp": "Up",
        "settings.stageMoveDown": "Down",
        "settings.stageRemove": "Remove",
        "settings.stageConfigPattern": "Regex Pattern",
        "settings.stageConfigReplacement": "Replacement",
        "settings.stageConfigTemplate": "Template ({{text}})",
        "settings.stageConfigStyle": "Comment Style",
        "settings.stageConfigPrompt": "LLM Prompt",
        "stage.smartPunctuation": "Smart Punctuation",
        "stage.fillerRemoval": "Filler Removal",
        "stage.whitespaceNormalize": "Whitespace Normalize",
        "stage.regexReplace": "Regex Replace",
        "stage.templateApply": "Template Apply",
        "stage.codeCommentTemplate": "Code Comment Template",
        "stage.llmRewrite": "LLM Rewrite",
        "settings.models": "Local Models",
        "settings.modelRefresh": "Refresh Models",
        "settings.modelPath": "Install Path",
        "settings.modelQuickStatus": "Quick Status",
        "settings.modelVerifyStatus": "Verification",
        "settings.modelVerify": "Verify",
        "settings.modelRetry": "Retry Download",
        "settings.modelCleanup": "Cleanup",
        "settings.modelQuickInstalled": "Installed",
        "settings.modelQuickSizeMismatch": "Size mismatch",
        "settings.modelQuickPartialOnly": "Partial file only",
        "settings.modelQuickNotInstalled": "Not installed",
        "settings.modelVerifyChecking": "Checking",
        "settings.modelVerifyNotChecked": "Not checked",
        "settings.modelVerifyValid": "Valid",
        "settings.modelVerifyMissing": "Missing",
        "settings.modelVerifySizeMismatch": "Size mismatch",
        "settings.modelVerifyChecksumMismatch": "Checksum mismatch",
        "settings.modelVerifyInvalid": "Invalid",
        "settings.download": "Download",
        "settings.remove": "Remove",
        "settings.save": "Save",
        "settings.saved": "Saved",
    ]

    private let japanese: [String: String] = [
        "tab.live": "ライブ",
        "tab.history": "履歴",
        "tab.settings": "設定",
        "status": "状態",
        "start": "開始",
        "stop": "停止",
        "clear": "クリア",
        "refine": "校正",
        "speak": "読み上げ",
        "transcribeFile": "ファイル変換",
        "partial": "途中結果",
        "final": "最終結果",
        "live.codexOAuthLogin": "Codex ログイン",
        "live.oauthOpenBrowser": "ブラウザで開く",
        "live.oauthClose": "閉じる",
        "history.search": "履歴テキストを検索",
        "history.refresh": "更新",
        "history.exportTxt": "TXT 出力",
        "history.exportMd": "MD 出力",
        "history.exportJson": "JSON 出力",
        "history.audioAssets": "音声アセット",
        "history.sessions": "セッション一覧",
        "history.segments": "文字起こしセグメント",
        "history.exports": "エクスポート",
        "history.noAudioAssets": "このセッションに利用可能な音声はありません",
        "history.playAudio": "音声再生",
        "history.stopAudio": "停止",
        "history.retranscribeAudio": "再文字起こし",
        "history.deleteAudio": "音声を削除",
        "history.deleteSession": "セッション削除",
        "settings.apiKey": "OpenAI API キー",
        "settings.sectionGeneral": "一般",
        "settings.sectionAccess": "認証情報",
        "settings.sectionPipeline": "パイプライン",
        "settings.sectionModels": "ローカルモデル",
        "settings.locale": "UI 言語",
        "settings.primaryStt": "主音声認識",
        "settings.localFallback": "ローカルフォールバック",
        "settings.refinePrimary": "校正プロバイダ",
        "settings.ttsPrimary": "TTS プロバイダ",
        "settings.hotkey": "グローバルショートカット",
        "settings.hotkeyCurrent": "現在のショートカット",
        "settings.hotkeyCaptureStart": "ショートカットを記録",
        "settings.hotkeyCaptureStop": "記録停止",
        "settings.hotkeyReset": "既定値に戻す",
        "settings.hotkeyHint": "修飾キー（⌘ / ⇧ / ⌥ / ⌃）を1つ以上含めてください。",
        "settings.hotkeyRecordingHint": "新しいショートカットを押してください。Esc でキャンセルします。",
        "settings.hotkeyNeedModifier": "ショートカットには修飾キーが必要です",
        "settings.hotkeyCaptureCancelled": "ショートカット記録をキャンセルしました",
        "settings.codexToken": "Codex Access Token",
        "settings.codexAccount": "Codex Account ID",
        "settings.importCodex": "Codex から導入",
        "settings.codexOAuth": "Codex OAuth ログイン",
        "settings.codexOAuthStatus": "ログイン状態",
        "settings.codexOAuthSource": "認証ファイル",
        "settings.codexOAuthLastRefresh": "最終更新",
        "settings.codexOAuthCode": "デバイスコード",
        "settings.codexOAuthCopyCode": "コードをコピー",
        "settings.codexOAuthCopyURL": "リンクをコピー",
        "settings.codexAuthMode": "認証方式",
        "settings.codexAuthModeOAuth": "OAuth デバイスログイン",
        "settings.codexAuthModeManual": "手動トークン入力",
        "settings.codexOAuthStep1": "デバイスログインを開始",
        "settings.codexOAuthStep2": "認証リンクを開き、デバイスコードをコピー",
        "settings.codexOAuthStep3": "ブラウザ承認後に状態を更新",
        "settings.codexManualTokenHint": "手動モードでは Token/Account ID のみ入力し、OAuth は実行しません。",
        "settings.codexOAuthStart": "デバイスログイン開始",
        "settings.codexOAuthCancel": "キャンセル",
        "settings.codexOAuthRefresh": "状態更新",
        "settings.codexOAuthLogout": "ログアウト",
        "settings.defaultPipeline": "既定テキストパイプライン",
        "settings.noPipeline": "利用可能なパイプラインがありません",
        "settings.pipelineEditor": "テキストパイプライン編集",
        "settings.pipelineList": "編集中のパイプライン",
        "settings.pipelineNew": "新規作成",
        "settings.pipelineDuplicate": "複製",
        "settings.pipelineDelete": "削除",
        "settings.pipelineName": "パイプライン名",
        "settings.pipelineEnabled": "パイプラインを有効化",
        "settings.pipelineStages": "ステージ",
        "settings.stageEnabled": "有効",
        "settings.stageType": "ステージ種別",
        "settings.stageAdd": "ステージ追加",
        "settings.stageMoveUp": "上へ",
        "settings.stageMoveDown": "下へ",
        "settings.stageRemove": "削除",
        "settings.stageConfigPattern": "正規表現パターン",
        "settings.stageConfigReplacement": "置換文字列",
        "settings.stageConfigTemplate": "テンプレート（{{text}}）",
        "settings.stageConfigStyle": "コメントスタイル",
        "settings.stageConfigPrompt": "LLM プロンプト",
        "stage.smartPunctuation": "句読点補正",
        "stage.fillerRemoval": "フィラー除去",
        "stage.whitespaceNormalize": "空白正規化",
        "stage.regexReplace": "正規表現置換",
        "stage.templateApply": "テンプレート適用",
        "stage.codeCommentTemplate": "コードコメントテンプレート",
        "stage.llmRewrite": "LLM リライト",
        "settings.models": "ローカルモデル",
        "settings.modelRefresh": "モデル更新",
        "settings.modelPath": "インストール先",
        "settings.modelQuickStatus": "クイックステータス",
        "settings.modelVerifyStatus": "検証状態",
        "settings.modelVerify": "検証",
        "settings.modelRetry": "再ダウンロード",
        "settings.modelCleanup": "残留をクリーンアップ",
        "settings.modelQuickInstalled": "インストール済み",
        "settings.modelQuickSizeMismatch": "サイズ不一致",
        "settings.modelQuickPartialOnly": "未完了ファイルのみ",
        "settings.modelQuickNotInstalled": "未インストール",
        "settings.modelVerifyChecking": "検証中",
        "settings.modelVerifyNotChecked": "未検証",
        "settings.modelVerifyValid": "有効",
        "settings.modelVerifyMissing": "ファイルなし",
        "settings.modelVerifySizeMismatch": "サイズ不一致",
        "settings.modelVerifyChecksumMismatch": "ハッシュ不一致",
        "settings.modelVerifyInvalid": "無効",
        "settings.download": "ダウンロード",
        "settings.remove": "削除",
        "settings.save": "保存",
        "settings.saved": "保存済み",
    ]
}
